# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsummary',
            name='complaints_count',
            field=models.IntegerField(default=0),
        ),
    ]
