# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaints_manager', '0002_personsummary_complaints_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
